import { useState } from "react";
import type { ConversationEntry } from "@workspace/api-client-react";
import { Markdown } from "@/components/ui/markdown";
import { PlanTrace } from "./PlanTrace";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { FileText, Clock, DollarSign, ChevronDown, ChevronRight, CornerDownRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { cn } from "@/lib/utils";

interface MessageBubbleProps {
  message: any; // Using any temporarily since the extended fields aren't in the exact ConversationEntry type generated by orval
  onClarify?: (text: string) => void;
  isLast?: boolean;
}

export function MessageBubble({ message, onClarify, isLast }: MessageBubbleProps) {
  const [clarification, setClarification] = useState("");
  const isUser = message.role === "user";
  const [extractedOpen, setExtractedOpen] = useState(false);

  if (isUser) {
    return (
      <div className="flex justify-end mb-6 animate-in slide-in-from-right-4 fade-in duration-300">
        <div className="max-w-[85%] bg-primary text-primary-foreground rounded-2xl rounded-tr-sm px-5 py-3.5 shadow-sm">
          {message.content && (
            <div className="text-sm whitespace-pre-wrap leading-relaxed">{message.content}</div>
          )}
          {message.files && message.files.length > 0 && (
            <div className="flex flex-wrap gap-2 mt-3">
              {message.files.map((file: string, i: number) => (
                <div key={i} className="flex items-center gap-1.5 bg-primary-foreground/10 px-2.5 py-1 rounded-md text-xs font-medium">
                  <FileText className="w-3.5 h-3.5 opacity-70" />
                  <span className="truncate max-w-[150px]">{file}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    );
  }

  // Assistant message
  return (
    <div className="flex justify-start mb-8 animate-in slide-in-from-left-4 fade-in duration-300">
      <div className="max-w-[90%] md:max-w-[85%] w-full">
        {/* Meta Header */}
        <div className="flex items-center gap-3 mb-2 ml-1">
          <div className="flex items-center justify-center w-6 h-6 rounded-md bg-primary/20 text-primary">
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
          </div>
          <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Agent</span>
          
          <div className="flex-1" />
          
          {(message.duration_seconds || message.cost_estimate) && (
            <div className="flex items-center gap-2 text-xs text-muted-foreground font-mono">
              {message.duration_seconds && (
                <span className="flex items-center gap-1"><Clock className="w-3 h-3" /> {message.duration_seconds}s</span>
              )}
              {message.cost_estimate && (
                <span className="flex items-center gap-1"><DollarSign className="w-3 h-3" /> {message.cost_estimate}</span>
              )}
            </div>
          )}
        </div>

        <div className="bg-card border border-border shadow-sm rounded-2xl rounded-tl-sm overflow-hidden transition-all">
          
          {/* Plan Trace section */}
          {message.plan_trace && message.plan_trace.length > 0 && (
            <PlanTrace steps={message.plan_trace} defaultOpen={isLast && message.status !== 'success'} />
          )}

          {/* Extracted Text Collapsible */}
          {message.extracted_text && (
            <div className="border-b border-border/50">
              <Collapsible open={extractedOpen} onOpenChange={setExtractedOpen}>
                <CollapsibleTrigger className="flex items-center gap-2 w-full px-5 py-2.5 text-xs font-medium text-muted-foreground hover:text-foreground transition-colors hover:bg-muted/30">
                  {extractedOpen ? <ChevronDown className="w-3.5 h-3.5" /> : <ChevronRight className="w-3.5 h-3.5" />}
                  <FileText className="w-3.5 h-3.5" />
                  View Extracted Document Text
                </CollapsibleTrigger>
                <CollapsibleContent>
                  <div className="px-5 pb-4 pt-1">
                    <div className="bg-muted/50 rounded-md p-3 max-h-[250px] overflow-y-auto">
                      <pre className="text-[11px] font-mono whitespace-pre-wrap text-muted-foreground">{message.extracted_text}</pre>
                    </div>
                  </div>
                </CollapsibleContent>
              </Collapsible>
            </div>
          )}

          {/* Main Answer Content */}
          {message.content && (
            <div className="px-5 py-4">
              <Markdown content={message.content} />
            </div>
          )}

          {/* Clarification Input (if needed) */}
          {message.status === "needs_clarification" && onClarify && isLast && (
            <div className="p-5 bg-primary/5 border-t border-primary/10">
              <div className="flex items-start gap-2 mb-3">
                <CornerDownRight className="w-4 h-4 mt-0.5 text-primary" />
                <span className="text-sm font-medium text-primary">Needs more information to proceed</span>
              </div>
              <div className="flex gap-2">
                <Input
                  value={clarification}
                  onChange={(e) => setClarification(e.target.value)}
                  placeholder="Type your clarification here..."
                  className="flex-1 bg-background border-primary/20 focus-visible:ring-primary/50"
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && clarification.trim()) {
                      onClarify(clarification);
                      setClarification("");
                    }
                  }}
                />
                <Button 
                  onClick={() => {
                    if (clarification.trim()) {
                      onClarify(clarification);
                      setClarification("");
                    }
                  }}
                  disabled={!clarification.trim()}
                >
                  Reply
                </Button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
